### ISSUE TITLE
Import fails because of wrong schema

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/realtimebus-v2#7]
When trying to import data I get the following error message:
```
 ERROR: ========================================================= (vdv.js:246)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]: ERROR: ==================== Import failed! ===================== (vdv.js:247)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]: ERROR: ========================================================= (vdv.js:248)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]: ERROR: Error: ERROR:  relation "data.rec_path" does not exist
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:     at module.exports.Client._readError (/home/jenkins/realtimebus-v2/node_modules/pg-native/index.js:80:13)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:     at module.exports.Client._read (/home/jenkins/realtimebus-v2/node_modules/pg-native/index.js:121:19)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:     at PQ.emit (events.js:321:20)
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:     at PQ.EventEmitter.emit (domain.js:485:12) {
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   severity: 'ERROR',
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   sqlState: '42P01',
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   messagePrimary: 'relation "data.rec_path" does not exist',
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   sourceFile: 'namespace.c',
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   sourceLine: '421',
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]:   sourceFunction: 'RangeVarGetRelidExtended'
Feb 14 08:02:18 ip-172-31-33-221 realtimebus[30295]: } (vdv.js:250)

```
I guess this happens because i didn't do a new installation from scratch but used the current underlying database.
@danielrampanelli Is there a schema migration strategy or do we have to reinstall the project every time we make changes to the schema?

**Comment by danielrampanelli** [comment]
As of now, the schema is correctly constructed (based on incremental changesets) only during a new installation (when using the "tools/setup.sh" script). It is obviously possible to prepare a "migrate" command/script for applying changes to an existing installation, without resorting to a complete bootstrap of the project.

**Comment by bertolla** [comment]
Ok than let's add this a s a future improvement. The import worked correctly

**Comment by Piiit** [comment]
Archiving
